"""empty message

Revision ID: 89eeb265f9b0
Revises: 
Create Date: 2025-01-31 08:43:56.526754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89eeb265f9b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
